// rick_and_morty 11_13/src/components/Menu.jsx
import {Link} from 'react-router-dom';

function Menu() {
    return (
      <div className="navbar bg-sky-400">
        <div className="flex-1">
          <Link to="/" className="btn btn-ghost text-xl">Rick and Morty</Link>
        </div>
        <div className="flex-none">
          <ul className="menu menu-horizontal px-1">
            <li>
              <Link to="/characters">Szereplok</Link>
            </li>
            <li>
              <Link to="/episodes">Epizodok</Link>
            </li>
            <li>
              <Link to="/locations">Helyszinek</Link>
            </li>
          </ul>
        </div>
      </div>
    );
  }
  
  export default Menu;

// vue_proba/src/components/Menu.vue
<script setup>
import {RouterLink} from 'vue-router'
</script>

<template>
  <div class="navbar bg-green-400 shadow-sm">
    <div class="flex-1">
      <RouterLink to="/" class="btn btn-ghost text-xl">Vue Test Menu</RouterLink>
    </div>
    <div class="flex-none">
      <ul class="menu menu-horizontal px-1">
        <li><RouterLink to="/typicode">Typicode</RouterLink></li>
        <li><RouterLink to="/randomusers">Randomusers</RouterLink></li>
        <li>
          <details>
            <summary>Parent</summary>
            <ul class="bg-base-100 rounded-t-none p-2">
              <li><a>Link 1</a></li>
              <li><a>Link 2</a></li>
            </ul>
          </details>
        </li>
      </ul>
    </div>
  </div>
</template>
