// reaact_typescript 03_03/src/components/RandomUsers.tsx
import { useEffect,useState } from "react"
import { RandUser } from "../types/RandomUser";
import UserCard from "./UserCard";


// type Name={
//     "title":string,
//     "first":string,
//     "last":string,
// }

// type RandUser={
//     "gender":string,
//     "name":{
//         "title":string,
//         "first":string,
//         "last":string
//     },
//     // name:Name,
//     location:{
//         street:{
//             "number":number,
//             "name":string
//         },
//         "city":string,
//         "state":string,
//         "country":string,
//         "postcode":string
//         coordinate:{
//             "latitude":string,
//             "longitude":string
//         },
//         "timezone":{
//             "offset":string,
//             "description":string
//         }
//     },
//     email:string,
//     login:{
//         "uuid":string,
//         "username":string,
//         "password":string,
//         "salt":string,
//         "md5":string,
//         "sha1":string,
//         "sha256":string
//     },
//     dob:{
//         "date":string,
//         "age":number
//     },
//     registered:{
//         "date":string,
//         "age":number
//     },
//     "phone":string,
//     "cell":string,
//     id:{
//         "name":string,
//         "value":string
//     },
//     pictures:{
//         "large": string,
//         "medium": string,
//         "thumbnail": string
//     },
//     "nat":string,
// }


function RandomUsers() {

    const [users,setUsers]=useState(Array<RandUser>)

    useEffect(()=>{
        fetch('https://randomuser.me/api/?results=30')
        .then(res=>res.json())
        .then(adat=>setUsers(adat.results))
        .catch(err=>alert(err));
    },[])

  return (
    <div className="flex flex-row flex-wrap items-center">
        {
            users.map((user,i)=>(<UserCard key={i} user={user}/>))
        }
    </div>
  )
}

export default RandomUsers

// vue_proba/src/components/Randomusers.vue
<script setup>
import { ref, onMounted } from 'vue'
import Randomuser from './Randomuser.vue'

const users = ref([]);

const fetchUsers=()=>{
    fetch('https://randomuser.me/api/?results=50')
    .then(res=>res.json())
    .then(adat=>users.value=adat.results)
    .catch(err=>console.log(err));
}
onMounted(fetchUsers)
</script>


<template>
        <!-- <div class="flex flex-row flex-wrap items-center justify-center m-5">
            <div v-for="user in users" class="m-5">
                <Randomuser :user="user" />
            </div>
        </div> -->
    <div class="gird grid-cols-3">
        <div v-for="user in users" class="m-5">
                <Randomuser :user="user" />
        </div>
    </div>
</template>
