// vue_proba/src/components/Main.vue
<script setup></script>

<template>
  <div class="hero bg-green-300 min-h-screen">
    <div class="hero-content flex-col lg:flex-row-reverse">
      <div class="text-center lg:text-left">
        <h1 class="text-5xl font-bold">Login now!</h1>
        <p class="py-6">
          Provident cupiditate voluptatem et in. Quaerat fugiat ut assumenda excepturi
          exercitationem quasi. In deleniti eaque aut repudiandae et a id nisi.
        </p>
      </div>
      <div class="card bg-green-400 w-full max-w-sm shrink-0 shadow-2xl">
        <div class="card-body">
          <fieldset class="fieldset">
            <label class="fieldset-label">Email</label>
            <input type="email" class="input" placeholder="Email" />
            <label class="fieldset-label">Password</label>
            <input type="password" class="input" placeholder="Password" />
            <div><a class="link link-hover">Forgot password?</a></div>
            <button class="btn btn-success mt-4">Login</button>
          </fieldset>
        </div>
      </div>
    </div>
  </div>
</template>

// reactr 11_13/src/components/Main.jsx
function Main() {
  return (
    <div className="hero bg-sky-300 min-h-screen">
      <div className="hero-content flex-col lg:flex-row">
        <img
          src="https://rickandmortyapi.com/api/character/avatar/1.jpeg"
          className="max-w-sm rounded-lg shadow-2xl"
        />
        <div>
          <h1 className="text-5xl font-bold">Rick and Morty API</h1>
          <p className="py-6">
            Provident cupiditate voluptatem et in. Quaerat fugiat ut assumenda
            excepturi exercitationem quasi. In deleniti eaque aut repudiandae et
            a id nisi.
          </p>
          <button className="btn btn-primary">Start</button>
        </div>
      </div>
    </div>
  );
}

export default Main;
